name: Build and deploy to vercel
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
        env:
          API_URL: ${{ secrets.API_URL }}
      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      OUTPUT_PATH: dist/mean
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: angular-app
          path: dist
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy '${{ env.OUTPUT_PATH }}' --yes --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
